### PR TITLE
Fix the findPassword method

### PR DESCRIPTION
**Pull request by cbargren**
Fixes the findPassword method so that it calls the right `operate` method.

### CODE REVIEW

**Comment by cbargren** [comment]
BTW, what do you think about changing the `findPassword` method to just return the whole object of passwords under the specified account? Or maybe just adding a new method that does that? I was also thinking about adding a method that clears out all the passwords under an account.

**Comment by maxkorp** [comment]
The api is built specifically to be a 1 to 1 match for atom/node-keytar. I'd be fine adding a `findAllPasswords` method though.

**Comment by maxkorp** [comment]
@cbargren is that something you'd want before I push a new version?
Edit: I pushed it up as 0.2.1 (previously 0.2.0).

**Comment by cbargren** [comment]
That's fine. I don't currently have any implementation of it yet and I have other stuff to do right now, but if I get an itch or it turns out I need it now, I'll open a PR for it.

**Comment by cbargren** [comment]
Thanks!

**Pull request merged**
